version: 2.1
orbs:
    rollbar: rollbar/deploy@dev:0.0.1
jobs:
  build:
    docker:
      - image: debian:stretch
    environment:
      ROlLBAR_ACCESS_TOKEN: cfbd66fad45a42e1b6aec0e587719cb9
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - rollbar/notify_deploy:
          name: Notify ROlLBAR
          environment: production
