version: 2
jobs:
  build:
    docker:
    - image: debian:stretch
    environment:
    - ROlLBAR_ACCESS_TOKEN: cfbd66fad45a42e1b6aec0e587719cb9
    steps:
    - checkout
    - run:
        name: Greeting
        command: echo Hello, world.
    - run:
        name: Print the Current Time
        command: date
    - run:
        name: Check for CURL
        command: |
          if [[ $(command -v curl) == "" ]]; then
            echo "curl is required to nofify Rollbar and is not available."
            exit 1
          fi
    - run:
        name: Notify Rollbar
        command: |
          curl https://api.rollbar.com/api/1/deploy/ \
            --form access_token=$ROLLBAR_ACCESS_TOKEN \
            --form environment=production \
            --form revision=$CIRCLE_SHA1 \
            --form local_username=$CIRCLE_USERNAME
workflows:
  version: 2
  workflow:
    jobs:
    - build

# Original config.yml file:
# version: 2.1
# orbs:
#     rollbar:
#       description: |
#         Commands for calling the Rollbar API.
# 
#         The source for the Orb can be found here:
#         https:\/\/github.com\/rollbar\/rollbar-orb\/tree\/master\/src\/rollbar
# 
#       commands:
#         notify_deploy:
#           description: |
#             A step to notify Rollbar the project has been deployed.
#             A Rollbar access token is required to be set in the
#             environment with the name `ROLLBAR_ACCESS_TOKEN`.
#             Add this as the last step of your the job that you
#             use to deploy.
#           parameters:
#             environment:
#               type: string
#               default: production
#               description: The Rollbar environment. Defaults to production.
#           steps:
#             - run:
#                 name: Check for CURL
#                 command: |
#                   if [[ $(command -v curl) == \"\" ]]; then
#                     echo \"curl is required to nofify Rollbar and is not available.\"
#                     exit 1
#                   fi
#             - run:
#                 name: Notify Rollbar
#                 command: |
#                   curl https:\/\/api.rollbar.com\/api\/1\/deploy\/ \\
#                     --form access_token=$ROLLBAR_ACCESS_TOKEN \\
#                     --form environment=<< parameters.environment >> \\
#                     --form revision=$CIRCLE_SHA1 \\
#                     --form local_username=$CIRCLE_USERNAME
#       jobs:
#         notify_deploy:
#           description: |
#             A job to notify Rollbar the project has been deployed.
#             A Rollbar access token is required to be set in the
#             environment with the name `ROLLBAR_ACCESS_TOKEN`.
#           parameters:
#             environment:
#               type: string
#               default: production
#               description: The Rollbar environment. Defaults to production.
#           docker:
#             - image: circleci\/buildpack-deps:18.04-scm
#           steps:
#             - notify_deploy:
#                 environment: << parameters.environment >>
# 
# jobs:
#   build:
#     docker:
#       - image: debian:stretch
#     environment:
#       ROlLBAR_ACCESS_TOKEN: cfbd66fad45a42e1b6aec0e587719cb9
#     steps:
#       - checkout
#       - run:
#           name: Greeting
#           command: echo Hello, world.
#       - run:
#           name: Print the Current Time
#           command: date
#       - rollbar\/notify_deploy:
#           environment: production
